name: 💡 Feature Request
description: Request a new feature
title: "[FEATURE]: "
labels: ["feature", "enhancement"]
body:
  - type: textarea
    id: what-do-you-need
    attributes:
      label: What do you need?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what do you need!
    validations:
      required: true
  - type: markdown
    attributes:
      value: By submitting this issue, you agree to follow our [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md).
