name: ❓ Question
description: I have a question and Google can't help me
title: "[QUESTION]: "
labels: ["question"]
body:
  - type: textarea
    attributes:
      label: What's your question?
      description: Tell us, what are your concerns young padawan!
      placeholder: How do I use the Force to sense and understand the world around me better?
    validations:
      required: true
  - type: markdown
    attributes:
      value: By submitting this issue, you agree to follow our [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md).
